server:
  port: 8081
spring:
  application.name: module-one
  liquibase:
    change-log: classpath:changelog/changelog-master.xml
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:advancedbackend}
    username: ${DB_USERNAME:advancedbackend}
    password: ${DB_PASSWORD:advancedbackend}
  jpa:
    show-sql: true
